### ISSUE TITLE
Issues with DIND

### ISSUE THREAD

**Issue by jacobnollette-luminfire** [humanmade/plugin-tester#6]
Getting an issue with DIND; using this in a CI pipeline.
`ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
`
The phpunit tests runs, but the docker container fails to exit, even though the pipeline succeeds. Any insight?

**Comment by rmccue** [comment]
Sounds like this is the same issue as https://github.com/jpetazzo/dind/issues/89 - generally, this (I believe) is an issue with your Docker daemon more generally, not with the container. Specifically the way it integrates with systemd and the caps involved IIRC.

Hope that helps!
